# Generated by Django 4.2.16 on 2025-08-20 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name_plural': 'カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='タグ')),
            ],
            options={
                'verbose_name_plural': 'タグ',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(max_length=512, verbose_name='タイトル')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('favicon_url', models.URLField(blank=True, max_length=255)),
                ('og_title', models.CharField(blank=True, max_length=512)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og_images/')),
                ('og_type', models.CharField(blank=True, max_length=50)),
                ('og_site_name', models.CharField(blank=True, max_length=512)),
                ('last_metadata_update', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookmark.category', verbose_name='カテゴリ')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='bookmark.tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name_plural': 'アイテム',
                'ordering': ('-id',),
            },
        ),
    ]
