# Generated by Django 4.2.16 on 2025-08-22 11:23

import bookmark.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=bookmark.models.upload_to_favicon),
        ),
        migrations.AlterField(
            model_name='item',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to=bookmark.models.upload_to_og_image),
        ),
    ]
